fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"

  repositories:
# profile module layout, default include ntp module
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"

  symlinks:
    profile_haproxy: "#{source_dir}"
